### ISSUE TITLE
Reproducing unnamed struct warnings

### ISSUE THREAD

**Issue by Mark-Nawar** [Mark-Nawar/re2r#5]

**Comment by Mark-Nawar** [comment]
@tdhock @narayanibarve I tried to reproduce this warning locally and it took me some time as starting GCC 8 and above ,C++11 will actually allow you to use a unnamed struct if it is defined in a named struct , Quoting from GCC documentation : ``` As permitted by ISO C11 and for compatibility with other compilers, GCC allows you to define a structure or union that contains, as fields, structures and unions without names. For example: ```
```cpp
struct {
  int a;
  union {
    int b;
    float c;
  };
  int d;
} foo;
```
here is the warning reproduction command just make sure you change this line ``` -I"/home/mark/Desktop/re2Google/re2/" ``` to your local re2 dir: 
```bash
mark@mark-VirtualBox:~/Desktop/re2Google/re2$ g++ -fsanitize=undefined,bounds-strict -fno-omit-frame-pointer -std=gnu++11 -I"/home/mark/Desktop/re2Google/re2/" -I"/usr/local/lib/R/include" -DNDEBUG -I../inst/include -DNDEBUG -I'/home/docker/R/Rcpp/include' -I'/home/docker/R/RcppParallel/include' -I/usr/local/include   -fpic  -g -O2 -Wall -pedantic -mtune=native  -c re2/regexp.h
```
here is the output: 
```bash
re2/regexp.h:572:5: warning: ISO C++ prohibits anonymous structs [-Wpedantic]
  572 |     };
      |     ^
re2/regexp.h:576:5: warning: ISO C++ prohibits anonymous structs [-Wpedantic]
  576 |     };
      |     ^
re2/regexp.h:580:5: warning: ISO C++ prohibits anonymous structs [-Wpedantic]
  580 |     };
      |     ^
re2/regexp.h:587:5: warning: ISO C++ prohibits anonymous structs [-Wpedantic]
  587 |     };
```
@narayanibarve , I do you have any think you want me to add when I put this upstream? I believe this might be solved by wrapping the structs in a named struct or a union.
this the G++ version I am using: 
```bash
mark@mark-VirtualBox:~/Desktop/re2Google/re2$ g++ --version
g++ (Ubuntu 9.3.0-17ubuntu1~20.04) 9.3.0
Copyright (C) 2019 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by tdhock** [comment]
Hi Mark this is good that you have a g++ version, command line, and expected error output. That should be very helpful for the upstream devs to reproduce this problem. You should go ahead and report this upstream as an issue. Make sure to include all these details, and why we need it fixed (for the CRAN checks). Maybe suggest one of those possible fixes in the issue and ask if they want you to submit a PR to fix that.

**Comment by Mark-Nawar** [comment]
yes surly , here is the [issue](https://github.com/google/re2/issues/319)

**Comment by tdhock** [comment]
so the upstream has written https://github.com/google/re2/issues/319#issuecomment-881382972 that there is another version of re2 C++ code already on CRAN, which is great. 
https://cloud.r-project.org/web/packages/re2
Can you please get in touch with the maintainer on github, https://github.com/girishji/re2 and explain that you are working on this for GSOC, and ask if there is anything else you can do to help with maintenance/ issue fixing in the next few weeks? 
Could you work on documentation of the changes that were necessary to the C++ code, in order to get the package accepted on CRAN? (that would be useful in case there are any changes to the upstream C++ code)

**Comment by Mark-Nawar** [comment]
yes I contacted the maintainer and I will share what I will do through an email. Whenever the maintainer reply.
Thank You
